# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=200)),
                ('author_name', models.CharField(max_length=200)),
                ('link_addr', models.CharField(max_length=200)),
                ('pub_year', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
